image: node:18

before_script:
  - npm install -g expo-cli eas-cli

stages:          
  - build
  - deploy

build_app:
  stage: build
  script:
    - echo "Building the project..."
    - cd ./Frontend
    - npm install 
    - echo "Build complete."
  only:
    - master
    - main
  tags:
    - docker

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - cd ./Frontend
    - npm install expo
    - npm install -g eas-cli
    - export EXPO_TOKEN=$EXPO_TOKEN_ENV_VAR
    - eas update -p android --auto
    - echo "Deploy complete."
  only:
    - master
    - main
  tags:
    - docker
