image: node:18

stages:          
  - build
  - test
  - deploy

build_app:
  stage: build
  
  script:
    - echo "Building the project..."
    - cd ./Frontend
    - npm install 
    - echo "Build complete."
  only:
    - master

test_app:
  stage: test
  before_script:
    - npm ci # faster than npm install
  script:
    - npm test 
  artifacts:
    when: always
    reports:
      junit: jest-report.xml # Save test results as JUnit XML
    paths:
      - jest-report.xml # archive report
  only:
    - master

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - cd ./Frontend
    - npm install expo
    - npm install -g eas-cli
    - export EXPO_TOKEN=$EXPO_TOKEN_ENV_VAR
    - eas update -p android --auto
    - echo "Deploy complete."
  only:
    - master

    