image: node:18

stages:          
  - build
  - backend_test
  - frontend_test
  - deploy

build_app:
  stage: build
  
  script:
    - echo "Building the project..."
    - cd ./Frontend
    - npm install 
    - echo "Build complete."
  only:
    - master

backend_test:
  stage: backend_test
  script:
    - echo "Running backend tests..."
    - cd ./Backend-server
    - npm install
    - npm install --save-dev jest supertest mongodb-memory-server
    - npm test
  only: 
    - iteration3

frontend_test:
  stage: frontend_test
  script:
    - echo "Running frontend tests..."
    - cd ./Frontend
    - npm install
    - npm install babel-preset-expo @babel/preset-flow metro-react-native-babel-preset react-native-dotenv --save-dev
    - npx jest --clearCache
    - npm test
  only:
    - iteration3

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - cd ./Frontend
    - npm install expo
    - npm install -g eas-cli
    - export EXPO_TOKEN=$EXPO_TOKEN_ENV_VAR
    - eas update -p android --auto
    - echo "Deploy complete."
  only:
    - master

    