image: node:18

stages:          
  - build
  - test
  - deploy

build_app:
  stage: build
  
  script:
    - echo "Building the project..."
    - cd ./Frontend
    - npm install 
    - echo "Build complete."
  only:
    - master

test_backend:
  stage: test
  script:
    - echo "Running backend tests..."
    - cd ./Backend-server
    - npm install
    - npm install --save-dev jest supertest mongodb-memory-server
    - npm test
  only:
    - automated-testing-test

test_frontend:
  stage: test
  script:
    - echo "Running frontend tests..."
    - cd ./Frontend
    - npm install
    - npm install --save-dev jest @testing-library/react-native react-test-renderer # should install test
    - npm test -- --detectOpenHandles --runInBand # for jest
  only:
    - automated-testing-test

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - cd ./Frontend
    - npm install expo
    - npm install -g eas-cli
    - export EXPO_TOKEN=$EXPO_TOKEN_ENV_VAR
    - eas update -p android --auto
    - echo "Deploy complete."
  only:
    - master

    