image: node:18

stages:          
  - build
  - deploy

build_app:
  stage: build
  
  script:
    - echo "Building the project..."
    - cd ./Frontend
    - npm install -g eas-cli
    - npm install 
    - echo "Build complete."
  only:
    - CItest

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - eas login --token OS3EHPkHik2nqiuyRf75UoxVyWpjh80irX4m4qAv
    - eas update -p android
    - echo "Deploy complete."
  only:
    - CItest