image: node:18

stages:          
  - build
  - deploy

build_app:
  stage: build
  
  script:
    - echo "Testing the project..."
    - cd ./Frontend/app
    - npm install 
    - npm run web 
    - echo "Build complete."
  only:
    - CItest

deploy_app:
  stage: deploy
  script: 
    - echo "Deploying the project..."
    - npm run android
    - echo "Deploy complete."
  only:
    - CItest