services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workflow
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  expo:
    build: ./frontend
    ports:
      - "19006:19006"
    command: ["npx", "expo", "start", "--tunnel"]
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
