version: '3.8'
services:
  backend:
    build: ./Backend-server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workflow
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
